language: node_js
node_js:
- '8'

install:
  - npm install

jobs:
  include:
    - stage: test
      script:
       - node cli.js gh-status --url http://example.com -s pending -c ci-utils/lint -d 'lint started'
       - npm test
       - node cli.js gh-status --url http://example.com -s success -c ci-utils/lint -d 'lint ok'
    - stage: use
      script:
        - node cli.js gh-status --url http://example.com -s success -c ci-utils/status -d 'body text'
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then node cli.js gh-comment --comment "Hello *world*" --issue $TRAVIS_PULL_REQUEST; fi
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

stages:
  - test
  - use
  - name: release
    if: branch = master

cache:
  - npm
