language: node_js
node_js:
- '8'

install:
  - npm install
  - node cli.js gh-status --url http://example.com -s pending -c ci-utils/status -d 'body text'

jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: use
      script:
        - node cli.js gh-status --url http://example.com -s success -c ci-utils/status -d 'body text'
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

stages:
  - test
  - use
 - name: release
   if: branch = master

cache:
  - npm
