language: node_js
node_js:
- '8'

install:
  - npm install

jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: use
      script:
        - node index.js gh-status --url http://example.com -s pending -c ci-utils/status -d 'body text'
        - node index.js gh-status --url http://example.com -s success -c ci-utils/status -d 'body text'

stages:
  - test
  - use
#  - name: deploy
#    if: branch = master

cache:
  - npm
